platform :ios, '6.0'
pod 'AFNetworking', '~> 1.3.1'
pod 'TimeScroller', :git => 'https://github.com/cyrilwei/TimeScroller.git'
pod 'SSKeychain', '~> 1.1.0'
pod 'JSONKit', '~> 1.4'
pod 'Reveal-iOS-SDK'
pod 'TSMessages', :git => 'https://github.com/cyrilwei/TSMessages.git'
pod 'TCSelectors', '~> 0.0.2'
pod 'SDWebImage', '~> 3.4'
pod 'UIImage-Resize', '~> 1.0'
